/**
 * All user-facing strings. The UI is English (like the sibling projects);
 * change wording here, never inline in components.
 */
export const APP_NAME = 'SnackTrainer';

/** Public address of the deployed app, shown as a QR code in Menu → Share. */
export const SHARE_URL = 'https://CasperWollesen.github.io/SnackTrainer/';

export const WEEKDAY_NAMES = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'] as const;
export const WEEKDAY_SHORT = ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'] as const;
export const MONTH_NAMES = [
  'January', 'February', 'March', 'April', 'May', 'June',
  'July', 'August', 'September', 'October', 'November', 'December',
] as const;
export const MONTH_SHORT = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'] as const;

export const texts = {
  app: { name: APP_NAME, tagline: 'Exercise snacks, logged in seconds.' },
  common: {
    close: 'Close',
    cancel: 'Cancel',
    save: 'Save',
    delete: 'Delete',
    undo: 'Undo',
    back: 'Back',
    done: 'Done',
    edit: 'Edit',
    search: 'Search',
    reps: 'reps',
    repsShort: 'x',
    time: 'time',
    seconds: 's',
    minutes: 'min',
    loading: 'Loading…',
  },
  timer: {
    start: 'Start snack session',
    startHint: 'Runs a timer while you snack. Everything you log goes into this session.',
    running: 'Snack session',
    entries: (n: number) => (n === 1 ? '1 entry' : `${n} entries`),
    nothingYet: 'Nothing logged yet',
    log: 'Log',
    stop: 'Stop',
    keepGoing: 'Keep going',
    autoStopHint: (min: number) => `Stops by itself after ${min} min without activity.`,
    stoppingIn: (left: string) => `Stops in ${left} without activity`,
    timed: 'Timed',
    runningTag: 'Running',
  },
  nav: {
    mainMenu: 'Main menu',
    menu: 'Menu',
    exercisesHint: 'Catalogue, your own exercises, hidden ones',
    settingsHint: 'Backup, demo data, install',
    shareHint: 'QR code and link for a friend',
    splashHint: 'Replay the intro',
  },
  splash: {
    title: 'Splash screen',
    skip: 'Skip',
    /**
     * One is shown per splash, in this order (the first on the very first launch), then round again.
     * Add more at the end; nothing else needs to change.
     */
    messages: [
      { title: 'Exercise snacks, logged in seconds.', body: 'A few squats while the kettle boils, a plank before lunch. Tap Log, pick an exercise, done.' },
      { title: '100% private.', body: 'Everything stays on this phone. No account, no server, no tracking. Only you see your snacks.' },
      { title: 'Made by Casper Wollesen.', body: 'Built for my own snacks between everything else. Now it is yours too. Enjoy!' },
      { title: 'Small snacks add up.', body: 'Ten push-ups five times a day is 350 a week, without ever changing clothes.' },
      { title: 'Two reps beat zero reps.', body: 'No warm-up, no gym bag, no excuses. Just a little movement, right now.' },
      { title: 'Works offline.', body: 'Add it to your home screen and it opens like an app, signal or not.' },
      { title: 'Time a whole snack.', body: 'Start a snack session and everything you log lands together, with the clock running.' },
      { title: 'Stretching counts too.', body: 'Hold a hip flexor stretch for a minute and log it. Your back will thank you.' },
    ],
  },
  share: {
    title: 'Share',
    description: 'Let someone scan this code to open SnackTrainer on their phone. Only the link is shared, never your data.',
    qrLabel: (url: string) => `QR code for ${url}`,
    button: 'Share link',
    copy: 'Copy link',
    copied: 'Link copied',
    copyFailed: 'Could not copy. Select the address above instead.',
  },
  tabs: { today: 'Today', history: 'History', exercises: 'Exercises' },
  add: { log: 'Log' },
  relative: { today: 'Today', yesterday: 'Yesterday', tomorrow: 'Tomorrow' },
  today: {
    previousDay: 'Previous day',
    nextDay: 'Next day',
    jumpToToday: 'Jump to today',
    sessions: 'Sessions',
    session: (n: number) => (n === 1 ? '1 session' : `${n} sessions`),
    emptyTitle: 'No snacks yet',
    emptyText: 'Start a snack session to time it, or tap Log for a quick entry. Twenty push-ups take five seconds to log.',
    emptyPast: 'Nothing was logged this day.',
    logFirst: 'Log a snack',
    stats: { reps: 'Reps', time: 'Time', sessions: 'Sessions' },
  },
  history: {
    title: 'History',
    periodLabel: 'Period',
    periods: { day: 'Day', week: 'Week', month: 'Month', last7: '7 days', last31: '31 days' },
    period: {
      thisWeek: 'This week',
      lastWeek: 'Last week',
      thisMonth: 'This month',
      lastDays: (n: number) => `Last ${n} days`,
      days: (n: number) => `${n} days`,
    },
    previous: 'Previous period',
    next: 'Next period',
    now: 'Now',
    compared: (range: string) => `Compared with ${range}`,
    comparedSoFar: (range: string) => `Compared with the same days: ${range}`,
    deltaNew: 'new',
    filterLabel: 'Exercise',
    allExercises: 'All exercises',
    metric: { reps: 'Reps', time: 'Time', sessions: 'Sessions', label: 'Show' },
    chartLabel: 'Reps per day',
    chartLabelTime: 'Minutes per day',
    chartLabelWeek: 'Reps per week',
    chartLabelWeekTime: 'Minutes per week',
    byHour: 'By hour',
    byDay: 'By day',
    byHourHint: 'When during the day. Tap a bar for details.',
    byDayHint: 'Tap a day to look at it on its own.',
    trend: 'Trend',
    trendHint: (count: number, unit: string) => `The last ${count} ${unit}, ending with the one shown. Tap a bar to go there.`,
    trendUnits: { day: 'days', week: 'weeks', month: 'months', last7: '7-day windows', last31: '31-day windows' },
    trendAverage: (value: string) => `Average ${value}`,
    week: (n: number) => `Week ${n}`,
    stats: { reps: 'Reps', time: 'Time', sessions: 'Sessions', activeDays: 'Active days', entries: 'Entries' },
    days: 'Days',
    byExercise: 'By exercise',
    emptyTitle: 'Nothing here yet',
    emptyText: 'Once you log a few snacks, your days and totals show up here. Settings can add demo data if you just want to look around.',
    emptyPeriod: 'Nothing logged in this period.',
    openDay: 'Open day',
    openInToday: 'Open on Today',
    entries: (n: number) => (n === 1 ? '1 entry' : `${n} entries`),
    best: 'best',
    nerdToggle: 'Nerd view',
    nerdHint: 'Averages, records, streaks and when you snack.',
  },
  nerd: {
    title: 'Nerd view',
    period: 'This period',
    perActiveDay: 'Per active day',
    perSession: 'Per session',
    perSet: 'Per set',
    biggestSession: 'Biggest session',
    biggestDay: 'Biggest day',
    bestSet: 'Best set',
    longestHold: 'Longest hold',
    earliest: 'Earliest start',
    latest: 'Latest start',
    busiestHour: 'Busiest hour',
    busiestWeekday: 'Busiest weekday',
    exercisesUsed: 'Exercises used',
    timedSessions: 'Timed sessions',
    timedValue: (count: number, avg: string, total: string) => `${count} · avg ${avg} · total ${total}`,
    longestSession: 'Longest session',
    timeOfDay: 'Time of day',
    timeOfDayLabel: 'Entries per hour of day',
    weekdays: 'Weekdays',
    weekdaysLabel: 'Per weekday',
    allTime: 'All time',
    currentStreak: 'Current streak',
    longestStreak: 'Longest streak',
    firstSnack: 'First snack',
    activeDaysAllTime: 'Active days',
    days: (n: number) => (n === 1 ? '1 day' : `${n} days`),
    sessions: (n: string) => `${n} sessions`,
    entries: (n: string) => `${n} entries`,
    reps: (n: string) => `${n} reps`,
    none: '–',
    filterNote: (name: string) => `Only ${name}.`,
  },
  exercises: {
    title: 'Exercises',
    searchPlaceholder: 'Search exercises…',
    recent: 'Recent',
    all: 'All',
    noMatch: 'No exercise matches',
    addCustom: 'Add exercise',
    custom: 'Custom',
    builtIn: 'Built-in',
    lastUsed: 'Last',
    total: 'Total',
    never: 'Not logged yet',
    editCustom: 'Edit exercise',
    deleteCustom: 'Delete exercise',
    deleteCustomHint: 'Logged entries keep their numbers but show "Unknown exercise".',
    hidden: 'Hidden',
    showAllHidden: 'Show all',
    tidyTitle: 'Shorter list',
    tidyText: 'Hide the built-in exercises you have never logged. Hidden exercises stay out of the lists; their history is kept.',
    hideUnused: (n: number) => `Hide ${n} unused`,
    hiddenMatches: 'Hidden',
  },
  exercise: {
    total: 'Total',
    sessions: 'Sessions',
    bestSession: 'Best session',
    bestSet: 'Best set',
    notLogged: 'Not logged yet. Tap Log to add the first one.',
    chartDays: '4 weeks',
    chartWeeks: '26 weeks',
    chartRange: 'Chart range',
    best: 'Best',
    showMore: (n: number) => `Show all ${n}`,
    hide: 'Hide',
    show: 'Show again',
    hiddenNote: 'Hidden from the exercise lists. Its history still counts.',
    log: 'Log',
    edit: 'Edit',
    openDay: 'Open day',
  },
  exerciseEditor: {
    newTitle: 'New exercise',
    editTitle: 'Edit exercise',
    name: 'Name',
    namePlaceholder: 'e.g. Wall sit',
    emoji: 'Emoji',
    emojiHint: 'One character, optional',
    category: 'Category',
    mode: 'Logged as',
    modeReps: 'Reps',
    modeTime: 'Time',
    bodyweight: 'Bodyweight movement',
    nameRequired: 'Give the exercise a name.',
  },
  log: {
    title: 'Log a snack',
    pickTitle: 'What did you do?',
    amountTitle: (name: string) => name,
    changeExercise: 'Change exercise',
    modeReps: 'Reps',
    modeTime: 'Time',
    repsLabel: 'Reps',
    timeLabel: 'Time',
    decrease: 'One less',
    increase: 'One more',
    plus5: '+5',
    plus10: '+10',
    typeTotal: 'Type total',
    start: 'Start',
    pause: 'Pause',
    resume: 'Resume',
    reset: 'Reset',
    stopwatch: 'Stopwatch',
    manualTime: 'Or type minutes and seconds',
    minutes: 'min',
    seconds: 'sec',
    when: 'Time',
    whenNow: 'Now',
    whenHint: 'Change if you are logging something you did earlier.',
    save: 'Save',
    saveAndAnother: 'Save & add another',
    nothingToSave: 'Enter at least 1 rep or 1 second.',
    dateLabel: (day: string) => `Logging to ${day}`,
  },
  entry: {
    title: 'Entry',
    editTitle: 'Edit entry',
    at: 'at',
    delete: 'Delete entry',
    save: 'Save changes',
  },
  toast: {
    logged: (summary: string) => `Logged ${summary}`,
    updated: 'Entry updated',
    deleted: 'Entry deleted',
    restored: 'Entry restored',
    sessionStarted: 'Snack session started',
    sessionStopped: (duration: string) => `Session saved · ${duration}`,
    sessionDiscarded: 'Session stopped. Nothing was logged, so nothing was saved.',
    sessionAutoStopped: (duration: string, min: number) => `Session stopped by itself after ${min} min without activity · ${duration}`,
    sessionResumed: 'Session resumed',
    exerciseSaved: 'Exercise saved',
    exerciseDeleted: 'Exercise deleted',
    exerciseHidden: (name: string) => `${name} hidden`,
    exerciseShown: (name: string) => `${name} shown again`,
    exercisesHidden: (n: number) => (n === 1 ? '1 exercise hidden' : `${n} exercises hidden`),
    exercisesShown: (n: number) => (n === 1 ? '1 exercise shown again' : `${n} exercises shown again`),
    exported: 'Backup saved',
    imported: 'Backup imported',
    allDeleted: 'All data deleted',
    demoAdded: 'Demo data added',
    demoRemoved: 'Demo data removed',
    saveFailed: 'Could not save. Storage may be full or blocked.',
    corruptData: 'Stored data could not be read. Starting empty; the old data is kept until you save.',
  },
  update: { ready: 'New version ready', reload: 'Reload', later: 'Later' },
  settings: {
    title: 'Settings',
    install: {
      title: 'Install on your phone',
      description: 'Works offline and opens like an app.',
      button: 'Install',
      installed: 'Installed as an app.',
      ios: 'iPhone: Share → Add to Home Screen.',
      android: 'Android: use the Install button or the browser menu.',
      desktop: 'Desktop: use the install icon in the address bar.',
    },
    sessions: {
      title: 'Sessions',
      description: 'Entries logged within this many minutes of the previous one join the same session.',
      gapLabel: 'Session gap',
      gapUnit: 'minutes',
      timeoutLabel: 'Auto-stop a snack session after',
      timeoutHint: 'Minutes without activity. The session then ends at your last activity, not when it stops.',
    },
    backup: {
      title: 'Backup',
      description:
        'Everything is stored only in this browser. Export a file before switching phones or clearing site data.',
      storagePersisted: 'The browser has promised to keep this data.',
      storageNotPersisted: 'The browser may clear this data under storage pressure. Keep a backup.',
      export: 'Export backup',
      import: 'Import backup',
      importing: 'Reading…',
      previewTitle: 'Import this backup?',
      previewBody: 'Everything currently stored will be replaced.',
      previewSessions: (n: number) => `${n} sessions`,
      previewEntries: (n: number) => `${n} entries`,
      previewCustom: (n: number) => `${n} custom exercises`,
      previewRange: (from: string, to: string) => `${from} – ${to}`,
      previewExportedAt: (when: string) => `Exported ${when}`,
      confirm: 'Replace and import',
      cancel: 'Cancel',
      errors: {
        'not-json': 'That file is not JSON.',
        'not-backup': 'That file is not a SnackTrainer backup.',
        'unsupported-version': 'That backup was made with a newer version of the app.',
        'invalid-data': 'The backup contains invalid data and was not imported.',
        'read-failed': 'The file could not be read.',
      } as Record<string, string>,
    },
    demo: {
      title: 'Demo data',
      description:
        'Fills History with about four months of made-up snacks so you can see how it looks. Demo entries are marked and can be removed any time without touching your own.',
      add: 'Add demo data',
      replace: 'Refresh demo data',
      remove: (n: number) => `Remove demo data (${n})`,
      banner: 'Demo data is shown.',
      bannerHint: 'It is marked and removed without touching your own entries.',
      bannerRemove: 'Remove',
      tag: 'Demo',
    },
    danger: {
      title: 'Delete everything',
      description: 'Removes all sessions, entries and custom exercises from this browser.',
      button: 'Delete all data',
      confirm: 'Delete all sessions, entries and custom exercises? This cannot be undone.',
    },
    about: {
      title: 'About',
      version: (v: string) => `Version ${v}`,
      offline: 'No account, no server. Data lives in this browser only.',
    },
  },
} as const;
